# Site settings
title: John Louie
email: jwlouie@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jlouie95618.github.io" # the base hostname & protocol for your site
twitter_username: jwlouie19
github_username:  jlouie95618

# Build settings
markdown: kramdown
